sudo: false
branches:
  only:
  - source
language: node_js
node_js:
  - '8.11.3'
before_install:
  - npm i -g npm@5.6.0
install:
  - npm i npminstall && npminstall
before_script:
  - npm i -g hexo-cli
script:
  - hexo generate
after_script:
  - npminstall codecov && codecov
deploy:
  provider: pages
  local-dir: ./public
  target-branch: master
  fqdn: tech.tfcloud.top
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: source
notifications:
  slack:
    on_success: change